name: Deploy Main
on:
  push:
    branches: ["main"]

jobs:
  build:
    name: Build Web
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./flutter_front
    steps:
      - uses: actions/checkout@v3

      # Flutter 버전 고정 (예: 3.19.6)
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6'
          channel: 'stable'

      - run: flutter config --enable-web

      - name: Clean up cache and lock files
        run: |
          rm -rf .dart_tool/ pubspec.lock

      - name: Setting .env
        run: |
          echo "ACCESS_TOKEN_KEY=${{ secrets.ACCESS_TOKEN_KEY }}" >> .env
          echo "IP=${{ secrets.IP }}" >> .env
          echo "KUMOH42_FIND_ACCOUNT=${{ secrets.KUMOH42_FIND_ACCOUNT }}" >> .env
          echo "KUMOH42_REGISTER=${{ secrets.KUMOH42_REGISTER }}" >> .env
          echo "REFRESH_TOKEN_KEY=${{ secrets.REFRESH_TOKEN_KEY }}" >> .env
          cat .env

      - run: flutter pub get

      # (옵션) 의존성 업그레이드
      # - run: flutter pub upgrade

      - run: flutter pub run build_runner build --delete-conflicting-outputs

      - run: flutter build web --release

      - name: Upload build file
        uses: actions/upload-artifact@v4
        with:
          name: web-artifact
          path: flutter_front/build/web
          if-no-files-found: error

  deploy:
    name: Deploy Web to Aws S3
    runs-on: ubuntu-latest
    needs: build
    env:
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      AWS_EC2_METADATA_DISABLED: true
    steps:
      - name: Download build file
        uses: actions/download-artifact@v4
        with:
          name: web-artifact
          path: build/web
      - name: Sync Bucket
        run: aws s3 sync build/web ${{secrets.AWS_BUCKET_NAME}} --region ap-northeast-2 --delete
      - name: Invalidate cache CloudFront
        run: aws cloudfront create-invalidation --distribution-id ${{secrets.AWS_DISTRIBUTION_ID}} --paths "/*"
        continue-on-error: true
